"""add model histoty ticket

Revision ID: a359a8aec0ae
Revises: e1bfc68ba22c
Create Date: 2023-08-31 12:08:03.571390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a359a8aec0ae'
down_revision = 'e1bfc68ba22c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('send_to', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('city_from', sa.String(), nullable=True),
    sa.Column('city_to', sa.String(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('place', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_ticket_id'), 'history_ticket', ['id'], unique=False)
    op.create_index(op.f('ix_history_ticket_send_to'), 'history_ticket', ['send_to'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_ticket_send_to'), table_name='history_ticket')
    op.drop_index(op.f('ix_history_ticket_id'), table_name='history_ticket')
    op.drop_table('history_ticket')
    # ### end Alembic commands ###
