"""delete field

Revision ID: e1bfc68ba22c
Revises: a32549a677e5
Create Date: 2023-08-11 10:48:32.349426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e1bfc68ba22c"
down_revision = "a32549a677e5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Callbacks", "result_calculated")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Callbacks",
        sa.Column(
            "result_calculated",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
