"""add model

Revision ID: a32549a677e5
Revises: 
Create Date: 2023-08-10 17:50:43.653534

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a32549a677e5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Callbacks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email_login", sa.String(length=255), nullable=False),
        sa.Column("result_calculated", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Callbacks")
    # ### end Alembic commands ###
